// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrVXdqlAstxs5xHNk4ZSbInZ1yVF5OsJM',
    appId: '1:962559500797:web:2f292621d9108d26f1b994',
    messagingSenderId: '962559500797',
    projectId: 'nhom9-laptrinhdidong',
    authDomain: 'nhom9-laptrinhdidong.firebaseapp.com',
    storageBucket: 'nhom9-laptrinhdidong.firebasestorage.app',
    measurementId: 'G-39CF3K7QZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFodEJNP8R0RXAeiFSgQVJqcssNjmOYRw',
    appId: '1:962559500797:android:bfe22dde76a89ca8f1b994',
    messagingSenderId: '962559500797',
    projectId: 'nhom9-laptrinhdidong',
    storageBucket: 'nhom9-laptrinhdidong.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB7JzskvaNHchGlsqNnr0Rt-eiWKsTlCw',
    appId: '1:962559500797:ios:51a2b0d5de059c17f1b994',
    messagingSenderId: '962559500797',
    projectId: 'nhom9-laptrinhdidong',
    storageBucket: 'nhom9-laptrinhdidong.firebasestorage.app',
    iosClientId: '962559500797-ls25d3uj040nh0n5sdsi7kveuq1kstqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopBanDongHo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB7JzskvaNHchGlsqNnr0Rt-eiWKsTlCw',
    appId: '1:962559500797:ios:51a2b0d5de059c17f1b994',
    messagingSenderId: '962559500797',
    projectId: 'nhom9-laptrinhdidong',
    storageBucket: 'nhom9-laptrinhdidong.firebasestorage.app',
    iosClientId: '962559500797-ls25d3uj040nh0n5sdsi7kveuq1kstqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopBanDongHo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrVXdqlAstxs5xHNk4ZSbInZ1yVF5OsJM',
    appId: '1:962559500797:web:bdb80fe6f2836d75f1b994',
    messagingSenderId: '962559500797',
    projectId: 'nhom9-laptrinhdidong',
    authDomain: 'nhom9-laptrinhdidong.firebaseapp.com',
    storageBucket: 'nhom9-laptrinhdidong.firebasestorage.app',
    measurementId: 'G-32FLD11KMQ',
  );
}
